[package]
name = "rust_basic"
version = "0.1.0"
authors = ["Amit Mondal <Amitmondal@abc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
